services:
  # shop-service:
  #   build: .
  #   container_name: shop-service
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     # енвы подключения к БД
  #     DATABASE_PORT: "5432"
  #     DATABASE_USER: postgres
  #     DATABASE_PASSWORD: password
  #     DATABASE_NAME: shop
  #     DATABASE_HOST: db
  #     # порт сервиса
  #     SERVER_PORT: "8080"
  #     # Kafka
  #     KAFKA_BROKERS: kafka:9092
  #     # SMTP (Mailpit)
  #     SMTP_HOST: mailpit
  #     SMTP_PORT: "1025"
  #     SMTP_FROM: shop@localhost
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_started
  #     mailpit:
  #       condition: service_started
  #   networks:
  #     - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      # "./migrations/init.sql" - путь к миграциям БД
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      # 5433 на хосте, чтобы не конфликтовать с локальным Postgres из Homebrew.
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

#   kafka:
#     image: apache/kafka:3.9.0
#     container_name: kafka
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: broker,controller
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     ports:
#       - "9092:9092"
#     networks:
#       - internal

#   mailpit:
#     image: axllent/mailpit
#     container_name: mailpit
#     ports:
#       # SMTP
#       - "1025:1025"
#       # UI для просмотра писем: http://localhost:8025
#       - "8025:8025"
#     networks:
#       - internal

networks:
  internal:
