// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_sendcoin is a generated GoMock package.
package mock_sendcoin

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSendCoinService is a mock of SendCoinService interface.
type MockSendCoinService struct {
	ctrl     *gomock.Controller
	recorder *MockSendCoinServiceMockRecorder
}

// MockSendCoinServiceMockRecorder is the mock recorder for MockSendCoinService.
type MockSendCoinServiceMockRecorder struct {
	mock *MockSendCoinService
}

// NewMockSendCoinService creates a new mock instance.
func NewMockSendCoinService(ctrl *gomock.Controller) *MockSendCoinService {
	mock := &MockSendCoinService{ctrl: ctrl}
	mock.recorder = &MockSendCoinServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendCoinService) EXPECT() *MockSendCoinServiceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSendCoinService) Send(ctx context.Context, senderID int64, toUser string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, senderID, toUser, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSendCoinServiceMockRecorder) Send(ctx, senderID, toUser, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSendCoinService)(nil).Send), ctx, senderID, toUser, amount)
}
