// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "avito/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddCoins mocks base method.
func (m *MockUserRepository) AddCoins(ctx context.Context, amount, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCoins", ctx, amount, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCoins indicates an expected call of AddCoins.
func (mr *MockUserRepositoryMockRecorder) AddCoins(ctx, amount, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCoins", reflect.TypeOf((*MockUserRepository)(nil).AddCoins), ctx, amount, userID)
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, username, email, hashPassword string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, username, email, hashPassword)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, username, email, hashPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, username, email, hashPassword)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id int64) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(ctx context.Context, username string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), ctx, username)
}

// GetCoins mocks base method.
func (m *MockUserRepository) GetCoins(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoins", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoins indicates an expected call of GetCoins.
func (mr *MockUserRepositoryMockRecorder) GetCoins(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoins", reflect.TypeOf((*MockUserRepository)(nil).GetCoins), ctx, userID)
}

// SubstractCoins mocks base method.
func (m *MockUserRepository) SubstractCoins(ctx context.Context, amount, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubstractCoins", ctx, amount, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubstractCoins indicates an expected call of SubstractCoins.
func (mr *MockUserRepositoryMockRecorder) SubstractCoins(ctx, amount, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubstractCoins", reflect.TypeOf((*MockUserRepository)(nil).SubstractCoins), ctx, amount, userID)
}

// UpdateEmail mocks base method.
func (m *MockUserRepository) UpdateEmail(ctx context.Context, userID int64, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, userID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockUserRepositoryMockRecorder) UpdateEmail(ctx, userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockUserRepository)(nil).UpdateEmail), ctx, userID, email)
}

// MockCoinTransfersRepository is a mock of CoinTransfersRepository interface.
type MockCoinTransfersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCoinTransfersRepositoryMockRecorder
}

// MockCoinTransfersRepositoryMockRecorder is the mock recorder for MockCoinTransfersRepository.
type MockCoinTransfersRepositoryMockRecorder struct {
	mock *MockCoinTransfersRepository
}

// NewMockCoinTransfersRepository creates a new mock instance.
func NewMockCoinTransfersRepository(ctrl *gomock.Controller) *MockCoinTransfersRepository {
	mock := &MockCoinTransfersRepository{ctrl: ctrl}
	mock.recorder = &MockCoinTransfersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoinTransfersRepository) EXPECT() *MockCoinTransfersRepositoryMockRecorder {
	return m.recorder
}

// GetReceived mocks base method.
func (m *MockCoinTransfersRepository) GetReceived(ctx context.Context, userID int64) ([]model.ReceivedTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceived", ctx, userID)
	ret0, _ := ret[0].([]model.ReceivedTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceived indicates an expected call of GetReceived.
func (mr *MockCoinTransfersRepositoryMockRecorder) GetReceived(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceived", reflect.TypeOf((*MockCoinTransfersRepository)(nil).GetReceived), ctx, userID)
}

// GetSent mocks base method.
func (m *MockCoinTransfersRepository) GetSent(ctx context.Context, userID int64) ([]model.SentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSent", ctx, userID)
	ret0, _ := ret[0].([]model.SentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSent indicates an expected call of GetSent.
func (mr *MockCoinTransfersRepositoryMockRecorder) GetSent(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSent", reflect.TypeOf((*MockCoinTransfersRepository)(nil).GetSent), ctx, userID)
}

// MockPurchasesRepository is a mock of PurchasesRepository interface.
type MockPurchasesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPurchasesRepositoryMockRecorder
}

// MockPurchasesRepositoryMockRecorder is the mock recorder for MockPurchasesRepository.
type MockPurchasesRepositoryMockRecorder struct {
	mock *MockPurchasesRepository
}

// NewMockPurchasesRepository creates a new mock instance.
func NewMockPurchasesRepository(ctrl *gomock.Controller) *MockPurchasesRepository {
	mock := &MockPurchasesRepository{ctrl: ctrl}
	mock.recorder = &MockPurchasesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchasesRepository) EXPECT() *MockPurchasesRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPurchasesRepository) Create(ctx context.Context, userID, merchID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, merchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPurchasesRepositoryMockRecorder) Create(ctx, userID, merchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPurchasesRepository)(nil).Create), ctx, userID, merchID)
}

// GetInventory mocks base method.
func (m *MockPurchasesRepository) GetInventory(ctx context.Context, userID int64) ([]model.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", ctx, userID)
	ret0, _ := ret[0].([]model.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockPurchasesRepositoryMockRecorder) GetInventory(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockPurchasesRepository)(nil).GetInventory), ctx, userID)
}

// MockMerchRepository is a mock of MerchRepository interface.
type MockMerchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchRepositoryMockRecorder
}

// MockMerchRepositoryMockRecorder is the mock recorder for MockMerchRepository.
type MockMerchRepositoryMockRecorder struct {
	mock *MockMerchRepository
}

// NewMockMerchRepository creates a new mock instance.
func NewMockMerchRepository(ctrl *gomock.Controller) *MockMerchRepository {
	mock := &MockMerchRepository{ctrl: ctrl}
	mock.recorder = &MockMerchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchRepository) EXPECT() *MockMerchRepositoryMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockMerchRepository) GetByName(ctx context.Context, name string) (model.Merch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(model.Merch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockMerchRepositoryMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockMerchRepository)(nil).GetByName), ctx, name)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTransactor) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTransactorMockRecorder) Do(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTransactor)(nil).Do), ctx, fn)
}
